name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Esta es la acci√≥n oficial y actualizada
      - name: Buildozer Action
        uses: kivy/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
          command: buildozer android debug
          repository_display_name: "Mi App"

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: Mi_App_Instalable
          path: bin/*.apk
