name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev openjdk-17-jdk lld
          pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: Force Accept Android Licenses
        run: |
          # Instalamos las herramientas de l√≠nea de comandos de Android manualmente para aceptar licencias
          sudo apt-get install -y android-sdk
          yes | sdkmanager --licenses || true
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

      - name: Build with Buildozer
        run: |
          # Usamos un comando que limpia antes de empezar para evitar el error 100
          buildozer android clean
          yes | buildozer -v android debug
        env:
          LDFLAGS: "-fuse-ld=lld"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mi_APK_Instalable
          path: bin/*.apk
