name: Crear Mi APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Buildozer Action
        uses: ArtemSerebrenninkov/buildozer-action@v1
        with:
          command: buildozer android debug
      - name: Subir APK terminada
        uses: actions/upload-artifact@v4
        with:
          name: Mi_Aplicacion_Instalable
          path: bin/*.apk
