name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev openjdk-17-jdk lld
          pip install --upgrade pip
          pip install "Cython<3.0" buildozer

      - name: Install Android SDK
        run: |
          # Esto instala las herramientas necesarias y acepta las licencias a la fuerza
          sudo apt install -y android-sdk
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

      - name: Build with Buildozer
        run: |
          # Forzamos a Buildozer a correr sin importar fallos previos
          buildozer android clean
          yes | buildozer -v android debug
        env:
          LDFLAGS: "-fuse-ld=lld"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: App_Lista
          path: bin/*.apk
